# Generated by Django 3.2.10 on 2021-12-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211226_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='卡密'),
        ),
        migrations.AlterField(
            model_name='code',
            name='sku',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sku', verbose_name='兑换商品'),
        ),
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账')], default=0, verbose_name='状态'),
        ),
    ]
