# Generated by Django 3.2.10 on 2022-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_code_use_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='retry',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格')], default=0, verbose_name='状态'),
        ),
    ]
