# Generated by Django 3.2.10 on 2022-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220115_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
