# Generated by Django 3.2.12 on 2022-03-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220115_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='DongCard',
            fields=[
                ('cardCode', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='卡券产品编号')),
                ('cardName', models.CharField(max_length=50, verbose_name='卡券名称')),
                ('synchro', models.IntegerField(choices=[(1, '实时出码'), (2, '延时出码')], default=1, verbose_name='券商出码方式')),
                ('faceAmt', models.IntegerField(blank=True, null=True, verbose_name='卡券面值(元)')),
                ('productPrice', models.IntegerField(verbose_name='券商协议价格(元)')),
                ('listImg', models.CharField(max_length=150, verbose_name='列表图')),
                ('detailImg', models.CharField(max_length=150, verbose_name='详情图')),
                ('baseMapImg', models.CharField(blank=True, max_length=150, null=True, verbose_name='底图')),
                ('cardDesc', models.TextField(verbose_name='产品介绍')),
                ('codeValidity', models.CharField(blank=True, max_length=50, null=True, verbose_name='有效期yyyy-MM-dd HH:mm:ss')),
                ('remark', models.CharField(blank=True, max_length=150, null=True, verbose_name='附加内容')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity', verbose_name='所属活动')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consumer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '东莞卡券基本信息',
                'verbose_name_plural': '东莞卡券基本信息',
            },
        ),
        migrations.CreateModel(
            name='DongOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitTimestamp', models.CharField(max_length=50, verbose_name='请求时间戳')),
                ('orderId', models.CharField(max_length=50, verbose_name='换购订单号')),
                ('orderQuantity', models.IntegerField(verbose_name='换购数量')),
                ('orderTime', models.CharField(max_length=50, verbose_name='换购时间')),
                ('orderPrice', models.IntegerField(verbose_name='换购总金额')),
                ('orderPoints', models.IntegerField(verbose_name='换购积分数')),
                ('ext', models.TextField(verbose_name='扩展域')),
                ('exchangeCode', models.TextField(verbose_name='兑换编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dongcard', verbose_name='卡券批次号')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consumer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '东莞订单信息',
                'verbose_name_plural': '东莞订单信息',
            },
        ),
    ]
