# Generated by Django 3.2.12 on 2022-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dongcard_dongorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongorder',
            name='exchangeCode',
            field=models.TextField(null=True, verbose_name='兑换编码'),
        ),
    ]
