# Generated by Django 3.2.12 on 2022-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220421_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': '权益券', 'verbose_name_plural': '权益券'},
        ),
        migrations.AddField(
            model_name='sku',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='可用'),
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='权益券码'),
        ),
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格'), (5, '兑换卡密')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='outcard',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格'), (5, '兑换卡密')], default=0, verbose_name='状态'),
        ),
    ]
