# Generated by Django 3.2.12 on 2022-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220511_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='account',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='使用账号'),
        ),
        migrations.AlterField(
            model_name='outcard',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='卡密,分割'),
        ),
    ]
