# Generated by Django 3.2.10 on 2022-05-21 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220520_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcard',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 0, 0), verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='outcard',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='卡密,分割'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='at',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='At手机号'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='消息推送Token'),
        ),
    ]
