# Generated by Django 3.2.12 on 2022-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220521_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='appid',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='业务id'),
        ),
    ]
