# Generated by Django 3.2.12 on 2022-05-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_consumer_appid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.IntegerField(choices=[(0, '自动'), (1, '手工')], default=0),
        ),
    ]
