# Generated by Django 3.2.12 on 2022-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_channel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='at',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='At手机号'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='消息推送Token'),
        ),
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格'), (5, '兑换卡密'), (6, '过期'), (7, '待手工充值')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='outcard',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格'), (5, '兑换卡密'), (6, '过期'), (7, '待手工充值')], default=0, verbose_name='状态'),
        ),
    ]
