# Generated by Django 3.2.12 on 2022-07-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220601_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='ex_order',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='上游单号'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='source_id',
            field=models.IntegerField(choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充')], default=0),
        ),
    ]
