# Generated by Django 3.2.12 on 2022-07-27 15:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220702_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongcard',
            name='autoOut',
            field=models.BooleanField(default=False, verbose_name='直接外部卡密'),
        ),
        migrations.AddField(
            model_name='dongcard',
            name='style',
            field=models.BooleanField(choices=[(True, '可用'), (False, '停用')], default=True, verbose_name='卡券状态'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='source_id',
            field=models.IntegerField(choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充,接口21'), (4, '浦上淘宝直充,接口11'), (5, '浦上加油卡,接口4'), (6, '软客直冲,接口2.2'), (7, '浦上提卡,接口10')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='兑换说明'),
        ),
    ]
