# Generated by Django 3.2.10 on 2022-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220727_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='consumer',
        ),
        migrations.AddField(
            model_name='code',
            name='ex_id',
            field=models.IntegerField(choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充,接口21'), (4, '浦上淘宝直充,接口11'), (5, '浦上加油卡,接口4'), (6, '软客直冲,接口2.2')], default=-1, verbose_name='上游通道'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='source_id',
            field=models.IntegerField(choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充,接口21'), (4, '浦上淘宝直充,接口11'), (5, '浦上加油卡,接口4'), (6, '软客直冲,接口2.2')], default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格'), (5, '兑换卡密'), (6, '过期'), (7, '待手工充值'), (8, '待充值')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='outcard',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已兑换'), (2, '已到账'), (3, '充值失败'), (4, '未配置规格'), (5, '兑换卡密'), (6, '过期'), (7, '待手工充值'), (8, '待充值')], default=0, verbose_name='状态'),
        ),
    ]
