# Generated by Django 3.2.10 on 2022-08-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_code_ex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='ex_id',
            field=models.IntegerField(blank=True, choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充,接口21'), (4, '浦上淘宝直充,接口11'), (5, '浦上加油卡,接口4'), (6, '软客直冲,接口2.2')], default=None, null=True, verbose_name='上游通道'),
        ),
    ]
