# Generated by Django 3.2.10 on 2022-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220822_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(0, '进行中'), (1, '活动停止')], default=0, verbose_name='活动状态'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='source_id',
            field=models.IntegerField(choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充,接口21'), (4, '浦上淘宝直充,接口11'), (5, '浦上加油卡,接口4'), (6, '软客直冲,接口2.2'), (8, '浦上京东直充,接口22'), (9, '渡渡鸟,直充接口1.2')], default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='ex_id',
            field=models.IntegerField(blank=True, choices=[(0, '南京立方'), (1, '北京太平永顺'), (2, '新美科技'), (3, '浦上京东直充,接口21'), (4, '浦上淘宝直充,接口11'), (5, '浦上加油卡,接口4'), (6, '软客直冲,接口2.2'), (8, '浦上京东直充,接口22'), (9, '渡渡鸟,直充接口1.2')], default=None, null=True, verbose_name='上游通道'),
        ),
    ]
