# Generated by Django 3.2.10 on 2022-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20221024_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_time',
            field=models.DateTimeField(blank=True, default='datetime', null=True, verbose_name='到期时间'),
        ),
    ]
