# Generated by Django 3.2.10 on 2022-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_activity_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='到期时间'),
        ),
    ]
